# Generated by Django 5.1.3 on 2024-11-23 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('value', models.IntegerField(unique=True)),
                ('is_initial', models.BooleanField(default=False)),
                ('is_final', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['value'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('orderType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='orders.ordertype')),
                ('destinations', models.ManyToManyField(related_name='events_as_destination', related_query_name='event_destination', to='states.state')),
                ('sources', models.ManyToManyField(related_name='events_as_source', related_query_name='event_source', to='states.state')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
