# Generated by Django 5.1.3 on 2024-11-23 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('states', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='state',
            options={},
        ),
        migrations.RemoveField(
            model_name='state',
            name='value',
        ),
    ]
