# Generated by Django 5.1.3 on 2024-11-21 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('states', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='event',
        ),
        migrations.AddField(
            model_name='event',
            name='destinations',
            field=models.ManyToManyField(related_name='events_as_destination', related_query_name='event_destination', to='states.state'),
        ),
        migrations.AddField(
            model_name='event',
            name='sources',
            field=models.ManyToManyField(related_name='events_as_source', related_query_name='event_source', to='states.state'),
        ),
    ]
