# Generated by Django 5.1.3 on 2024-11-23 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('states', '0002_alter_state_options_remove_state_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='state',
            options={'ordering': ['id']},
        ),
    ]
